"""initial schema

Revision ID: fc567720fd49
Revises: 
Create Date: 2026-09-28 11:39:00.504579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc567720fd49'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('trees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trees_owner_id'), 'trees', ['owner_id'], unique=False)
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=False),
    sa.Column('given_name', sa.String(length=120), nullable=False),
    sa.Column('family_name', sa.String(length=120), nullable=True),
    sa.Column('sex', sa.Enum('female', 'male', 'unknown', name='sex'), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('birth_place', sa.String(length=200), nullable=True),
    sa.Column('death_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_tree_id'), 'people', ['tree_id'], unique=False)
    op.create_table('relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=False),
    sa.Column('person_a_id', sa.Integer(), nullable=False),
    sa.Column('person_b_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('parent', 'spouse', name='relation_kind'), nullable=False),
    sa.CheckConstraint('person_a_id <> person_b_id', name='ck_not_self'),
    sa.ForeignKeyConstraint(['person_a_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_b_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_a_id', 'person_b_id', 'kind', name='uq_relationship')
    )
    op.create_index(op.f('ix_relationships_tree_id'), 'relationships', ['tree_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relationships_tree_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_people_tree_id'), table_name='people')
    op.drop_table('people')
    op.drop_index(op.f('ix_trees_owner_id'), table_name='trees')
    op.drop_table('trees')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
